kind: pipeline

steps:
  - name: UnitTest
    image: maven:3-jdk-11
    commands:
      - mvn package
      - mvn test
  - name: Sonar
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=mora456 -Dsonar.host.url=http://52.188.188.66:9000
  - name: QualityGate
    image: maven:3-jdk-11
    commands:
      - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=mora456 -Dsonar.host.url=http://52.188.188.66:9000
  - name: Production
    image: maven:3-jdk-11
    commands:
      - mvn tomcat7:redeploy
  - name: Email
    image: drillster/drone-email
    settings:
      from: josuemorales123@gmail.com
      host: smtp.gmail.com
      port: 465
      username:
        from_secret: user
      password:
        from_secret: pass
      subject: Production Pipeline
      recipients:
        - morales181101@unis.edu.gt
    when:
      status:
        - success
        - failure
