kind: pipeline
steps:
- name: Install
  image: maven:3-jdk-11
  commands:
  - mvn clean install
  
- name: Package-master
  image: maven:3-jdk-11
  commands:
  - mvn clean package
  when:
    branch:
      - master
  
- name: Package-ventasDev
  image: maven:3-jdk-11
  commands:
  - mvn clean package
  when:
    branch:
      - ventasDev
  
- name: Package-ventasQA
  image: maven:3-jdk-11
  commands:
  - mvn clean package
  when:
    branch:
      - ventasQA
  
- name: Unit Testing
  image: maven:3-jdk-11
  commands:
  - mvn test
  
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=chema10 -Dsonar.host.url=https://swift-robin-87.loca.lt
  
- name: Deploy
  image: maven:3-jdk-11
  commands:
  - mvn tomcat7:redeploy

- name: Email Notification
  image: drillster/drone-email
  settings:
    from: jmyc9999@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: email
    password: 
      from_secret: pass_email
    subject: Pipeline 
    recipients:
        - jmyc9999@gmail.com
  when:
    status:
    - success
    - failure

- name: Slack Notificacion
  image: plugins/slack
  settings:
    webhook: 
      from_secret: webhookSlack
    channel: ventas
  when:
    status: [ success, failure ]
