kind: pipeline
steps:
- name: Install
  image: maven:3-jdk-11
  commands:
  - mvn install
- name: Package
  image: maven:3-jdk-11
  commands:
  - mvn package
- name: Unit Testing
  image: maven:3-jdk-11
  commands:
  - mvn test
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=chema10 -Dsonar.host.url=https://witty-gecko-69.loca.lt
- name: Production
  image: maven:3-jdk-11
  commands:
  - mvn tomcat7:deploy
